"""test_contracts.py — the Python client library as a READ-ONLY consumer of the
checked-in contract fixtures (§4). The spec deliberately COPIES wire shapes
across the hub/client boundary with no shared package; the fixtures are how both
copies answer to one oracle. This suite asserts that the library's copy still
matches — it never regenerates a fixture, and it never asserts server behavior.

Two fixtures are in scope for this library: the close-code table (codes and
upgrade statuses -> required client behavior) and the tunnel frames (the
``hub/register`` request, its ok reply, the ``hub/replaced`` notification). The
other fixtures — whoami, the error codes, the admin ops, the planner's rows —
belong to the CLI and scripts consumers. Exact filenames are pinned by the
producer, ``server/test/worker/contracts.test.ts``, at implementation; the names
used below (``contracts/close-codes.json``, ``contracts/tunnel-frames.json``)
follow it.

Runner: pytest, ``scripts`` + clients lane (§2). Plain file reads with
``json``/``pathlib`` — no network, no event loop, no ordering between cases; the
fixtures are the only thing this suite and the JS consumer share.

Cross-language agreement, stated once: the JS and Python reconnect tables are the
deliberate duplication (strategy §3). They are never compared to each other —
each is pinned to the same fixture here and in
``clients/js/test/contracts-consumer.test.ts``, so they agree transitively
through one oracle instead of through a shared runtime artifact. Both sides
carry a STRUCTURED trigger on the row and derive the fixture's canonical key
from it — ``_trigger_key`` here, ``triggerKey()`` there. One join key, one
division of labour.

AUTHORSHIP, load-bearing (strategy §9 rule 1): ``contracts/*.json`` is
owner-authored and regenerated by an owner-run ``pnpm contracts:update``, always
in its own commit; CI rejects a commit touching ``contracts/**`` together with
implementation files. Nothing here may write, patch, or "fix" a fixture — a red
case is a ``fix:``, ``spec:``, or ``test:`` decision (§8), never a fixture edit
made to go green.

The deps line below names the fixtures READ-ONLY, and that is the whole
governance rule restated as a dependency: nothing in this file writes to
``contracts/``.
"""

# deps: json + pathlib (fixture reads) · contracts/close-codes.json +
#   contracts/tunnel-frames.json (READ-ONLY; server/test/worker/contracts.test.ts
#   is their only writer, §4) · tests/test_transport.py (RECONNECT_ROWS,
#   UNLISTED_ROWS, ReconnectRow — safe to import because pytest collects by path,
#   so re-importing a test module re-collects nothing; the JS side had to move its
#   rows into a plain policy-rows.ts for exactly the opposite reason) ·
#   conftest.registry (the shared teardown — every case here opens a live hub) ·
#   pmcp_client (the frames the library emits)

import json
from pathlib import Path

import anyio
import pytest

import pmcp_client
from fake_hub import RegisterOutcome, start_fake_hub
from pmcp_client import caller
from test_transport import TOKEN, RECONNECT_ROWS, UNLISTED_ROWS, ReconnectRow, Trigger

# contracts/ lives at the repo root: tests/ -> py/ -> clients/ -> repo root.
_CONTRACTS_DIR = Path(__file__).resolve().parents[3] / "contracts"


def _fixture(name: str) -> dict:
    """One fixture, read from disk. Read-only, always — this suite never writes
    one (§4)."""
    return json.loads((_CONTRACTS_DIR / name).read_text(encoding="utf-8"))


_CLOSE_CODES = _fixture("close-codes.json")
_TUNNEL_FRAMES = _fixture("tunnel-frames.json")


def _trigger_key(trigger: Trigger) -> str:
    """The join key between a policy row and a fixture entry: the row carries a
    SHAPE and the fixture keys a string, so this is where the two meet — the
    same division of labour as the JS side's ``triggerKey()`` over its
    ``PolicyTrigger`` union. An ending with no code (a rejected registration, a
    bare drop) is keyed by its kind alone, which is exactly why the fixture does
    not key those two."""
    return f"{trigger.kind}:{trigger.code}" if trigger.code is not None else trigger.kind


def _behavior_of(row: ReconnectRow) -> str:
    """A row's required behavior in the fixture's own vocabulary."""
    if row.terminal and row.raises is not None:
        return "stop_fatal"
    if row.terminal:
        return "stop_quiet"
    return "reconnect"


# ── close codes -> client behavior · §4, §6 ───────────────────────────────────


def test_every_fixture_ending_has_a_policy_row() -> None:
    """§4 · every entry in contracts/close-codes.json — close codes 4000-4004 and
    the upgrade statuses 401/403 alike — has exactly one row in
    test_transport.RECONNECT_ROWS, so a code cannot enter the protocol without
    the client deciding what to do about it."""
    row_keys = [_trigger_key(row.trigger) for row in RECONNECT_ROWS]
    for key in _CLOSE_CODES["entries"]:
        assert row_keys.count(key) == 1, key


def test_every_policy_row_names_a_fixture_ending() -> None:
    """§4 · the reverse direction: every RECONNECT_ROWS trigger key is an entry
    the fixture defines — the table transcribes the oracle and never invents an
    ending."""
    for row in RECONNECT_ROWS:
        assert _trigger_key(row.trigger) in _CLOSE_CODES["entries"]


def test_no_unlisted_row_names_a_fixture_ending() -> None:
    """§4 · the escape hatch cannot become one: no row in
    test_transport.UNLISTED_ROWS names an entry the fixture defines, so the
    second table can only hold endings the fixture deliberately leaves unkeyed
    (a rejected registration, a bare drop, a code or status outside the
    vocabulary) and never a keyed ending smuggled out of the totality check
    above."""
    for row in UNLISTED_ROWS:
        assert _trigger_key(row.trigger) not in _CLOSE_CODES["entries"]


def test_row_behavior_agrees_with_the_fixture_behavior_word() -> None:
    """§4 · each row's consequences match the fixture's required-behavior word for
    that entry, and the fixture's vocabulary is closed — every word it uses is one
    a row can express, and no row needs a word it lacks, so a new behavior cannot
    appear on either side unnoticed. (Finding RESOLVED 2026-08-25, the same one the
    JS consumer recorded: contracts/README.md named four behaviors where the
    library headers named three. The pinned vocabulary is THREE — stop_fatal,
    stop_quiet, reconnect — with the fourth word split off as ReconnectRow's
    existing `schedule` attribute, exponential or max_only.)"""
    for row in RECONNECT_ROWS:
        entry = _CLOSE_CODES["entries"][_trigger_key(row.trigger)]
        assert _behavior_of(row) == entry["behavior"], row.trigger
        assert row.schedule == entry.get("schedule"), row.trigger


def test_behavior_and_schedule_stay_separate_axes() -> None:
    """§4 · a fixture entry's behavior is one of the three words and never a
    schedule, and only reconnect entries carry a schedule — so "retry at max
    backoff" cannot re-enter the vocabulary as a fourth behavior."""
    for key, entry in _CLOSE_CODES["entries"].items():
        assert entry["behavior"] in _CLOSE_CODES["behaviors"], key
        assert entry["behavior"] not in _CLOSE_CODES["schedules"], key
        if entry["behavior"] == "reconnect":
            assert entry.get("schedule") in _CLOSE_CODES["schedules"], key
        else:
            assert "schedule" not in entry, key


def test_behavior_words_map_onto_row_columns_both_ways() -> None:
    """§4 · the mapping is total in both directions — stop_quiet <-> terminal with
    no raises, stop_fatal <-> terminal with one, reconnect <-> not terminal — so
    neither the fixture nor ReconnectRow can grow an ending the other cannot
    say."""
    both = [*RECONNECT_ROWS, *UNLISTED_ROWS]
    settlements = {"stop_quiet", "stop_fatal", "reconnect"}
    used = {_behavior_of(row) for row in both}
    assert used == settlements
    for word in _CLOSE_CODES["behaviors"]:
        assert any(_behavior_of(row) == word for row in both), word
    for row in both:
        behavior = _behavior_of(row)
        assert behavior in settlements
        assert row.redials == (behavior == "reconnect")
        assert row.terminal == (behavior != "reconnect")
        assert (row.raises is not None) == (behavior == "stop_fatal")


# ── tunnel frames · §4, §6 ────────────────────────────────────────────────────


async def test_register_frame_matches_the_fixture_shape(registry) -> None:
    """§6 · the hub/register frame the library emits equals the fixture's request
    shape: the method name and the params keys clientVersion, protocolVersion,
    roles — and no service or slug field, ever."""
    hub = await start_fake_hub()
    transport = pmcp_client.HubTransport(hub.origin, TOKEN, {})
    registry.append((hub, transport))
    await transport.__aenter__()
    emitted = (await hub.next_frame(1)).message
    pinned = _TUNNEL_FRAMES["register"]["request"]
    assert emitted["jsonrpc"] == pinned["jsonrpc"]
    assert emitted["method"] == pinned["method"]
    assert sorted(emitted["params"].keys()) == sorted(pinned["params"].keys())
    for forbidden in _TUNNEL_FRAMES["register"]["forbiddenParamsKeys"]:
        assert forbidden not in emitted["params"]
        assert f'"{forbidden}"' not in json.dumps(emitted)


async def test_register_roles_value_is_the_fixtures_declaration_verbatim(registry) -> None:
    """§6/§20.3 · the roles VALUE the library sends is the fixture's own
    declaration, both spellings intact — a bare pattern list beside a per-family
    object, neither repaired on the way out.

    The shape case above compares params KEYS, which a library that flattened
    ``{"tools": ..., "prompts": ..., "resources": ...}`` to its tools would still
    satisfy. The declaration comes from the FIXTURE, never from a constant here:
    §20.3 gives the family vocabulary exactly one home and it is the hub's (§6),
    so the only thing this library owes it is verbatim transmission — in whichever
    of the two spellings the author chose, mixed across roles in one declaration if
    that is what they wrote. This is the library half of contracts.test.ts's "a
    shape change in either library fails here first": that case runs in workerd and
    cannot import this package, so the judgement of a library against that value
    happens on this side of the boundary."""
    declared = _TUNNEL_FRAMES["register"]["request"]["params"]["roles"]
    hub = await start_fake_hub()
    transport = pmcp_client.HubTransport(hub.origin, TOKEN, declared)
    registry.append((hub, transport))
    await transport.__aenter__()
    emitted = (await hub.next_frame(1)).message["params"]
    assert emitted["roles"] == declared


async def test_protocol_version_equals_the_fixture_revision(registry) -> None:
    """§6 · the protocolVersion the library sends is the fixture's pinned revision
    — a revision bump is an owner-run fixture commit, and this case is what makes
    the client's copy follow it."""
    hub = await start_fake_hub()
    transport = pmcp_client.HubTransport(hub.origin, TOKEN)
    registry.append((hub, transport))
    await transport.__aenter__()
    emitted = (await hub.next_frame(1)).message["params"]
    assert emitted["protocolVersion"] == _TUNNEL_FRAMES["protocolVersion"]
    assert pmcp_client.PROTOCOL_VERSION == _TUNNEL_FRAMES["protocolVersion"]


async def test_fixture_ok_and_rejection_replies_drive_both_paths(registry) -> None:
    """§6 · the fixture's ok reply completes registration and its rejection reply
    raises RegistrationError — both replayed as the fixture gives them with only
    the OBSERVED request id filled in. A fixture pins no per-run value
    (contracts/README, "nothing that varies per run"), so neither reply carries
    an ``id``; a byte-for-byte replay correlates to no request, leaves
    registration unanswered until the 10 s deadline, and lands on close 4004 —
    reconnect, not RegistrationError. The refusal beside its allow-twin, both
    read from the fixture rather than hand-spelled."""
    # The ack the client is answered with is the fixture's own frame, not a
    # paraphrase the harness synthesizes: a change to its shape must reach this
    # client, which is the entire point of a shared oracle.
    accepting = await start_fake_hub(registrations=[RegisterOutcome(frame=_TUNNEL_FRAMES["register"]["ack"])])
    good = pmcp_client.HubTransport(accepting.origin, TOKEN)
    registry.append((accepting, good))
    await good.__aenter__()  # must not raise

    refusing = await start_fake_hub(registrations=[RegisterOutcome(frame=_TUNNEL_FRAMES["register"]["rejection"])])
    bad = pmcp_client.HubTransport(refusing.origin, TOKEN, {"All": []})
    registry.append((refusing, bad))
    with pytest.raises(pmcp_client.RegistrationError):
        await bad.__aenter__()


async def test_hub_replaced_notification_is_recognized_verbatim(registry) -> None:
    """§6 · the fixture's hub/replaced notification drives the stop-quietly path:
    the library recognizes the pinned frame, not a paraphrase of it."""
    hub = await start_fake_hub()
    transport = pmcp_client.HubTransport(hub.origin, TOKEN)
    registry.append((hub, transport))
    read_stream, _write_stream = await transport.__aenter__()
    await hub.next_frame(1)
    await hub.send(_TUNNEL_FRAMES["replaced"])
    await hub.close_connection(4000)
    # Recognized means CONSUMED: the pinned notification never reaches the
    # session, and the 4000 close it precedes stops this copy quietly — `closed()`
    # returning rather than raising IS the stop_quiet ending.
    with anyio.fail_after(5):
        await transport.closed()
    with pytest.raises(anyio.EndOfStream):
        await read_stream.receive()


async def test_hub_control_methods_equal_the_set_consumed_internally(registry) -> None:
    """§6 · the set of hub/* methods the fixture defines equals the set the
    transport consumes internally — a method outside that set reaches the SDK
    session untouched, so a new control frame cannot be swallowed silently."""
    assert sorted(pmcp_client.HUB_METHODS.values()) == sorted(_TUNNEL_FRAMES["methods"].values())
    hub = await start_fake_hub()
    transport = pmcp_client.HubTransport(hub.origin, TOKEN)
    registry.append((hub, transport))
    read_stream, _write_stream = await transport.__aenter__()
    stranger = {"jsonrpc": "2.0", "id": 3, "method": "hub/something-new", "params": {}}
    await hub.send(stranger)
    item = await read_stream.receive()
    assert item.message.model_dump(by_alias=True, exclude_unset=True) == stranger


def test_caller_reads_the_fixtures_forwarded_meta_keys() -> None:
    """§7 · the forwarded-call ``_meta`` keys :func:`caller` reads are the
    fixture's ``forwardedCall.metaKeys``, read FROM the fixture and never
    hand-spelled: hub/principal and hub/roles land on principal and roles, and
    the third pinned key (io.modelcontextprotocol/clientCapabilities) reaches the
    SDK session untouched. This is the one tunnel-frames key whose consumer is
    the client library, and renaming it hub-side must fail here — silently,
    caller() would start answering principal "" and empty roles, and every
    service branching on a negative check (``if not caller.has_role("admin"):
    allow``) would flip open. §7 invites services to trust these values, which is
    what makes an unread fixture key a boundary and not cosmetics."""
    principal_key, roles_key, capabilities_key = _TUNNEL_FRAMES["forwardedCall"]["metaKeys"]
    meta = {principal_key: "sa:claude", roles_key: ["reader"], capabilities_key: {"sampling": {}}}
    identity = caller(meta)
    assert identity.principal == "sa:claude"
    assert identity.roles == ("reader",)
    assert identity.has_role("reader") is True
