"""test_contracts.py — the Python client library as a READ-ONLY consumer of the
checked-in contract fixtures (§4). The spec deliberately COPIES wire shapes
across the hub/client boundary with no shared package; the fixtures are how both
copies answer to one oracle. This suite asserts that the library's copy still
matches — it never regenerates a fixture, and it never asserts server behavior.

Two fixtures are in scope for this library: the close-code table (codes and
upgrade statuses -> required client behavior) and the tunnel frames (the
``hub/register`` request, its ok reply, the ``hub/replaced`` notification). The
other fixtures — whoami, the error codes, the admin ops, the planner's rows —
belong to the CLI and scripts consumers. Exact filenames are pinned by the
producer, ``server/test/worker/contracts.test.ts``, at implementation; the names
used below (``contracts/close-codes.json``, ``contracts/tunnel-frames.json``)
follow it.

Runner: pytest, ``scripts`` + clients lane (§2). Plain file reads with
``json``/``pathlib`` — no network, no event loop, no ordering between cases; the
fixtures are the only thing this suite and the JS consumer share.

Cross-language agreement, stated once: the JS and Python reconnect tables are the
deliberate duplication (strategy §3). They are never compared to each other —
each is pinned to the same fixture here and in
``clients/js/test/contracts-consumer.test.ts``, so they agree transitively
through one oracle instead of through a shared runtime artifact. Python rows
carry the fixture's canonical key verbatim in ``ReconnectRow.trigger``; the JS
rows derive the same key from a structured trigger. One join key, two spellings.

AUTHORSHIP, load-bearing (strategy §9 rule 1): ``contracts/*.json`` is
owner-authored and regenerated by an owner-run ``pnpm contracts:update``, always
in its own commit; CI rejects a commit touching ``contracts/**`` together with
implementation files. Nothing here may write, patch, or "fix" a fixture — a red
case is a ``fix:``, ``spec:``, or ``test:`` decision (§8), never a fixture edit
made to go green.

The deps line below names the fixtures READ-ONLY, and that is the whole
governance rule restated as a dependency: nothing in this file writes to
``contracts/``.
"""

# deps: json + pathlib (fixture reads) · contracts/close-codes.json +
#   contracts/tunnel-frames.json (READ-ONLY; server/test/worker/contracts.test.ts
#   is their only writer, §4) · tests/test_transport.py (RECONNECT_ROWS,
#   ReconnectRow) · pmcp_client (the frames the library emits)

import pytest

# Outline stage: every case below is authored and none is implemented, so the whole
# module is skipped rather than failing on NotImplementedError. Nothing here may go
# green until the case it names is actually written.
pytestmark = pytest.mark.skip(reason="outline")

# ── close codes -> client behavior · §4, §6 ───────────────────────────────────


def test_every_fixture_ending_has_a_policy_row() -> None:
    """§4 · every entry in contracts/close-codes.json — close codes 4000-4004 and
    the upgrade statuses 401/403 alike — has exactly one row in
    test_transport.RECONNECT_ROWS, so a code cannot enter the protocol without
    the client deciding what to do about it."""
    raise NotImplementedError


def test_every_policy_row_names_a_fixture_ending() -> None:
    """§4 · the reverse direction: every row's trigger key is an entry the fixture
    defines — the table transcribes the oracle and never invents an ending."""
    raise NotImplementedError


def test_row_behavior_agrees_with_the_fixture_behavior_word() -> None:
    """§4 · each row's consequences match the fixture's required-behavior word for
    that entry, and the fixture's vocabulary is closed — every word it uses is one
    a row can express, and no row needs a word it lacks, so a new behavior cannot
    appear on either side unnoticed. (Finding RESOLVED 2026-08-25, the same one the
    JS consumer recorded: contracts/README.md named four behaviors where the
    library headers named three. The pinned vocabulary is THREE — stop_fatal,
    stop_quiet, reconnect — with the fourth word split off as ReconnectRow's
    existing `schedule` attribute, exponential or max_only.)"""
    raise NotImplementedError


def test_behavior_and_schedule_stay_separate_axes() -> None:
    """§4 · a fixture entry's behavior is one of the three words and never a
    schedule, and only reconnect entries carry a schedule — so "retry at max
    backoff" cannot re-enter the vocabulary as a fourth behavior."""
    raise NotImplementedError


def test_behavior_words_map_onto_row_columns_both_ways() -> None:
    """§4 · the mapping is total in both directions — stop_quiet <-> terminal with
    no raises, stop_fatal <-> terminal with one, reconnect <-> not terminal — so
    neither the fixture nor ReconnectRow can grow an ending the other cannot
    say."""
    raise NotImplementedError


# ── tunnel frames · §4, §6 ────────────────────────────────────────────────────


def test_register_frame_matches_the_fixture_shape() -> None:
    """§6 · the hub/register frame the library emits equals the fixture's request
    shape: the method name and the params keys clientVersion, protocolVersion,
    roles — and no service or slug field, ever."""
    raise NotImplementedError


def test_protocol_version_equals_the_fixture_revision() -> None:
    """§6 · the protocolVersion the library sends is the fixture's pinned revision
    — a revision bump is an owner-run fixture commit, and this case is what makes
    the client's copy follow it."""
    raise NotImplementedError


def test_fixture_ok_and_rejection_replies_drive_both_paths() -> None:
    """§6 · the fixture's ok reply, replayed verbatim, completes registration; its
    rejection reply, replayed verbatim, raises RegistrationError — the refusal
    beside its allow-twin, both read from the fixture rather than hand-spelled."""
    raise NotImplementedError


def test_hub_replaced_notification_is_recognized_verbatim() -> None:
    """§6 · the fixture's hub/replaced notification drives the stop-quietly path:
    the library recognizes the pinned frame, not a paraphrase of it."""
    raise NotImplementedError


def test_hub_control_methods_equal_the_set_consumed_internally() -> None:
    """§6 · the set of hub/* methods the fixture defines equals the set the
    transport consumes internally — a method outside that set reaches the SDK
    session untouched, so a new control frame cannot be swallowed silently."""
    raise NotImplementedError
