/**
 * clients/js/test/contracts-consumer.test.ts — the JS client library as a
 * READ-ONLY consumer of the checked-in contract fixtures (§4). The spec
 * deliberately COPIES wire shapes across the hub/client boundary with no shared
 * package; the fixtures are how both copies answer to one oracle. This suite
 * asserts that the library's copy still matches — it never regenerates a
 * fixture, and it never asserts server behavior.
 *
 * Two fixtures are in scope for this library: the close-code table (codes and
 * upgrade statuses → required client behavior) and the tunnel frames (the
 * hub/register request, its ok reply, the hub/replaced notification). The other
 * fixtures — whoami, the error codes, the admin ops, the planner's rows — belong
 * to the CLI and scripts consumers. Exact filenames are pinned by the producer,
 * `server/test/worker/contracts.test.ts`, at implementation; the names used
 * below (contracts/close-codes.json, contracts/tunnel-frames.json) follow it.
 *
 * Project: `scripts` + clients (plain Node, parallel). The fixtures are files on
 * disk read with node:fs — no worker, no network, no ordering between cases.
 *
 * AUTHORSHIP, load-bearing (strategy §9 rule 1): `contracts/*.json` is
 * owner-authored and regenerated by an owner-run `pnpm contracts:update`, always
 * in its own commit; CI rejects a commit touching contracts/** together with
 * implementation files. Nothing in this file may write, patch, or "fix" a
 * fixture — a red case here is a `fix:`, `spec:`, or `test:` decision (§8),
 * never a fixture edit made to go green.
 *
 * Why totality is the point: the close-code table's value is that no protocol
 * code can be added without the client deciding what to do about it. So the
 * assertions below run in BOTH directions — every fixture entry has a policy
 * row, and every policy row names a fixture entry.
 */

// deps: node:fs (fixture reads) · ./transport.test (reconnectPolicyRows, ReconnectPolicyRow) · clients/js/src/index.ts (HubTransport's emitted frames) · contracts/close-codes.json + contracts/tunnel-frames.json (read-only)

import { describe, it } from "vitest";
import type { ReconnectPolicyRow } from "./transport.test";

describe("close codes → client behavior · §4, §6", () => {
  it.todo("§4 · every entry in contracts/close-codes.json — close codes 4000–4004 and the upgrade statuses 401/403 alike — has exactly one row in transport.test.ts's reconnectPolicyRows");
  it.todo("§4 · every reconnect-policy row names an entry the fixture defines: the table transcribes the oracle and never invents an ending of its own");
  it.todo("§4 · each row's required behavior agrees with the fixture's behavior word for that entry — the fixture's vocabulary is the vocabulary, so a fifth behavior cannot appear on either side unnoticed");
  it.todo("§4 · the fixture's behavior vocabulary is closed: every word it uses is one the policy table can express, and no row needs a word it lacks — so a new behavior is a spec change, not a silent addition (finding RESOLVED 2026-08-25: contracts/README.md named FOUR behaviors while the library headers named three, folding max backoff into \"reconnect\". The pinned vocabulary is THREE — stop_fatal, stop_quiet, reconnect — with the fourth word split off as a separate `schedule` attribute, exponential or max_only, which is the shape both row types already carried. README, both client headers and both tables now spell it that one way)");
  it.todo("§4 · the two axes stay separate: a fixture entry's behavior is one of the three words and never a schedule, and only reconnect entries carry a schedule — so \"retry at max backoff\" cannot re-enter as a behavior");
  it.todo("§4 · the mapping is total in both directions — stop_quiet ↔ resolve, stop_fatal ↔ reject, reconnect ↔ pending — so neither the fixture nor ReconnectPolicyRow can grow an ending the other cannot say");
});

describe("tunnel frames · §4, §6", () => {
  it.todo("§6 · the hub/register frame the library emits deep-equals the fixture's request shape: the method name and the params keys clientVersion, protocolVersion, roles — and no service or slug field, ever, because identity comes exclusively from the token");
  it.todo("§6 · the protocolVersion the library sends equals the fixture's pinned revision — a revision bump is a fixture commit, owner-run, and this case is what makes the client's copy follow it");
  it.todo("§6 · the fixture's ok reply, replayed verbatim, completes registration; the fixture's rejection reply, replayed verbatim, produces RegistrationError — the refusal beside its allow-twin, both read from the fixture");
  it.todo("§6 · the fixture's hub/replaced notification, replayed verbatim, drives the stop-quietly path: the library recognizes the pinned frame, not a paraphrase of it");
  it.todo("§6 · the set of hub/* control methods in the fixture equals the set the transport consumes internally — a method outside that set reaches the SDK session untouched, so a new control frame cannot be swallowed silently");
});

/**
 * The join key between a policy row and a fixture entry: one canonical string
 * per ending (an upgrade status, a close code, a rejected registration, a plain
 * drop). It exists so the two totality checks above are set comparisons rather
 * than nested loops with bespoke matching — and so the shape of the fixture's
 * keys is decided once, here, instead of at each call site. The Python consumer
 * derives the same keys from the same fixture.
 */
export function triggerKey(trigger: ReconnectPolicyRow["trigger"]): string {
  // deps: none
  throw new Error("unimplemented");
}
